---
name: Build and Test

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
  # Run this every Sunday morning at 4am,
  # so that we at least become aware, if/when
  # it breaks due to env/dependency updates.
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:

jobs:
  macos-build:
    runs-on: macos-latest
    strategy:
      matrix:
        java: ['8', '11', '17', '21']

    steps:
      - name: Set up Doxygen
        run: brew install doxygen

      - uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          architecture: arm64
          distribution: zulu
          cache: maven

      - name: Build/test code with Maven
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            --file pom.xml \
            install

      - name: Upload CodeCov Report
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.java == '8'
