name: Build and Test

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main


jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          architecture: x64

      - name: Install Doxygen
        run: brew install doxygen

      - name: Build/test code with Maven
        run: mvn -B cobertura:cobertura install --file pom.xml
      - run: mkdir staging && cp casampledsp-complete/target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

      - name: Upload CodeCov Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ always() }}

      - name: Build site with Maven
        run: mvn -B clean site --file pom.xml
